"use client";
import { useState } from "react";
import { toast } from "sonner";
import { reportMember, toggleMemberBlock } from "@/actions/member.actions";

export default function MemberSafetyActions({ memberId, initiallyBlocked }) {
  const [blocked, setBlocked] = useState(initiallyBlocked); const [reporting, setReporting] = useState(false);
  return <div className="flex flex-wrap gap-2 print:hidden"><button onClick={async () => { const result = await toggleMemberBlock(memberId); if (result.error) toast.error(result.error); else { setBlocked(result.blocked); toast.success(result.blocked ? "Member blocked" : "Member unblocked"); } }} className="border rounded-lg px-3 py-2 text-sm">{blocked ? "Unblock" : "Block"}</button><button onClick={() => setReporting(true)} className="border rounded-lg px-3 py-2 text-sm text-red-700">Report</button>{reporting && <form className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await reportMember(memberId, data.get("category"), data.get("details")); result.error ? toast.error(result.error) : (toast.success("Report sent to GGF moderators"), setReporting(false)); }}><div className="bg-white rounded-xl p-6 w-full max-w-md"><h2 className="font-bold text-xl">Report member</h2><label htmlFor="report-category" className="block text-sm font-medium mt-4">Reason</label><select id="report-category" name="category" className="border rounded-lg p-3 w-full mt-1"><option value="spam">Spam</option><option value="harassment">Harassment</option><option value="misrepresentation">Misrepresentation</option><option value="other">Other</option></select><label htmlFor="report-details" className="block text-sm font-medium mt-3">Details</label><textarea id="report-details" name="details" maxLength={1000} className="border rounded-lg p-3 w-full mt-1"/><div className="flex justify-end gap-3 mt-4"><button type="button" onClick={() => setReporting(false)}>Cancel</button><button className="bg-red-700 text-white rounded-lg px-4 py-2">Send report</button></div></div></form>}</div>;
}
