import Link from "next/link";
import Image from "next/image";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";

export const dynamic = "force-dynamic";
export default async function DirectoryPage({ searchParams }) {
  const params = await searchParams; const query = (params.q || "").trim(); const page = Math.max(1, Number(params.page) || 1); const session = await auth();
  const blockFilter = session ? { blocksCreated: { none: { blockedId: session.user.id } }, blocksReceived: { none: { blockerId: session.user.id } } } : {};
  const where = { isActive: true, isDirectoryVisible: true, ...blockFilter, ...(query ? { OR: [{ firstName: { contains: query, mode: "insensitive" } }, { surname: { contains: query, mode: "insensitive" } }, { profession: { contains: query, mode: "insensitive" } }, { village: { contains: query, mode: "insensitive" } }, { skills: { has: query } }] } : {}) };
  const [members, total] = await Promise.all([prisma.user.findMany({ where, select: { id: true, firstName: true, middleName: true, surname: true, photo: true, profession: true, education: true, skills: true, village: true }, orderBy: { firstName: "asc" }, skip: (page - 1) * 24, take: 24 }), prisma.user.count({ where })]);
  return <div className="py-12"><div className="container-custom"><h1 className="text-3xl font-bold">Member directory</h1><p className="text-gray-600 mt-2">Only members who opt in are shown.</p><form className="mt-6"><label htmlFor="directory-search" className="sr-only">Search members</label><input id="directory-search" name="q" defaultValue={query} placeholder="Search name, profession, village or skill" className="w-full max-w-xl border rounded-xl px-4 py-3"/></form><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 mt-8">{members.map((member) => <Link href={`/user/${member.id}`} key={member.id} className="border rounded-xl p-5 hover:shadow-md focus:ring-2 focus:ring-primary"><div className="flex gap-4">{member.photo ? <Image src={member.photo} alt="" width={64} height={64} className="rounded-full object-cover w-16 h-16"/> : <div className="w-16 h-16 rounded-full bg-primary-100 flex items-center justify-center text-primary font-bold">{member.firstName[0]}</div>}<div><h2 className="font-bold">{member.firstName} {member.middleName} {member.surname}</h2><p className="text-sm text-primary">{member.profession || member.education || "GGF Member"}</p><p className="text-xs text-gray-500">{member.village}</p></div></div>{member.skills.length > 0 && <div className="flex flex-wrap gap-2 mt-4">{member.skills.map((skill) => <span key={skill} className="bg-gray-100 text-xs px-2 py-1 rounded">{skill}</span>)}</div>}</Link>)}{!members.length && <p className="text-gray-500 col-span-full py-10">No matching opted-in members found.</p>}</div>{total > 24 && <nav aria-label="Member pages" className="flex justify-between mt-6"><Link className={page === 1 ? "invisible" : "text-primary"} href={{ pathname: "/directory", query: { q: query, page: page - 1 } }}>← Previous</Link><span>Page {page} of {Math.ceil(total / 24)}</span><Link className={page * 24 >= total ? "invisible" : "text-primary"} href={{ pathname: "/directory", query: { q: query, page: page + 1 } }}>Next →</Link></nav>}</div></div>;
}
