import Link from "next/link";
import { prisma } from "@/lib/prisma";

export const metadata = { title: "Governance & Transparency - GGF" };
export const dynamic = "force-dynamic";

export default async function GovernancePage() {
  const organizers = await prisma.user.findMany({ where: { role: "ORGANIZER", isActive: true }, select: { id: true, firstName: true, middleName: true, surname: true, profession: true }, orderBy: [{ firstName: "asc" }, { surname: "asc" }] });
  return <div className="py-12"><div className="container-custom max-w-4xl"><h1 className="text-4xl font-bold">Governance & transparency</h1><p className="text-gray-600 mt-4">GGF is committed to clear event rules, responsible handling of member information and transparent community service.</p><div className="grid md:grid-cols-2 gap-5 mt-9"><section className="border rounded-xl p-6"><h2 className="font-bold text-xl">Event organizers</h2><div className="mt-3 space-y-2">{organizers.map(person => <div key={person.id}><p className="font-semibold">{person.firstName} {person.middleName} {person.surname}</p>{person.profession && <p className="text-sm text-gray-500">{person.profession}</p>}</div>)}{!organizers.length && <p className="text-gray-600">Organizer information will be published after verification.</p>}</div></section>{[["Community impact","Live portal totals show members, events, tournaments and certificates. Annual reports can add scholarships, volunteer hours and initiatives."],["Payments","Event payments are reviewed manually by authorized organizers. Members receive a status, reviewer outcome and a reason when correction is needed."],["Contact & grievances","Registration, privacy and conduct concerns can be submitted through the dedicated contact and grievance channel."]].map(([title,text])=><section key={title} className="border rounded-xl p-6"><h2 className="font-bold text-xl">{title}</h2><p className="text-gray-600 mt-2">{text}</p>{title === "Contact & grievances" && <Link href="/contact" className="inline-block text-primary mt-3">Contact GGF →</Link>}</section>)}</div><div className="flex flex-wrap gap-4 mt-8 text-primary"><Link href="/policies/privacy">Privacy policy</Link><Link href="/policies/terms">Terms of use</Link><Link href="/policies/payments">Payment & refund policy</Link><Link href="/policies/community">Community guidelines</Link></div></div></div>;
}
