import { prisma } from "@/lib/prisma";
import { Building2, Globe, Phone } from "lucide-react";

export const dynamic = "force-dynamic";
export default async function BusinessesPage({ searchParams }) {
  const query = ((await searchParams).q || "").trim();
  const items = await prisma.businessProfile.findMany({ where: { moderationStatus: "approved", ...(query ? { OR: [{ name: { contains: query, mode: "insensitive" } }, { category: { contains: query, mode: "insensitive" } }, { address: { contains: query, mode: "insensitive" } }] } : {}) }, include: { user: { select: { firstName: true, surname: true } } }, orderBy: { name: "asc" }, take: 100 });
  return <div className="py-12"><div className="container-custom"><h1 className="text-3xl font-bold">Community business directory</h1><p className="text-gray-600 mt-2">Approved businesses and professional services from GGF members.</p><a href="/businesses/manage" className="inline-block bg-primary text-white px-4 py-2 rounded-lg mt-4">Manage my listing</a><form className="mt-6"><label htmlFor="business-search" className="sr-only">Search businesses</label><input id="business-search" name="q" defaultValue={query} placeholder="Search business, service or location" className="border rounded-xl px-4 py-3 w-full max-w-xl"/></form><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-8">{items.map((item) => <article key={item.id} className="border rounded-xl p-5"><Building2 className="text-primary"/><h2 className="font-bold text-xl mt-3">{item.name}</h2><p className="text-primary text-sm">{item.category}</p><p className="text-gray-600 mt-3">{item.description}</p><p className="text-xs text-gray-500 mt-3">Member: {item.user.firstName} {item.user.surname}</p><div className="flex gap-3 mt-4">{item.phone && <a href={`tel:${item.phone}`} aria-label={`Call ${item.name}`}><Phone className="w-5 h-5"/></a>}{item.website && <a href={item.website} target="_blank" rel="noopener noreferrer" aria-label={`Open ${item.name} website`}><Globe className="w-5 h-5"/></a>}</div></article>)}{!items.length && <p className="text-gray-500 col-span-full py-10">No matching approved businesses.</p>}</div></div></div>;
}
