"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { checkInTicket, createAnnouncement, createVolunteerOpportunity, reviewBusiness, reviewCommunityReport, reviewOpportunity, sendEventReminder } from "@/actions/community-admin.actions";

export default function CommunityManager({ events, opportunities, businesses, volunteers, reports = [], isSuper = false }) {
  const router=useRouter(); const [checkin,setCheckin]=useState(null);
  async function run(action,success){const r=await action();r.error?toast.error(r.error):(toast.success(success),router.refresh());}
  return <div className={`space-y-8 ${!isSuper ? "[&>section:nth-of-type(n+4)]:hidden" : ""}`}>
    <section className="bg-white rounded-xl border p-6"><h2 className="font-bold text-xl">Publish announcement</h2><form className="grid gap-3 mt-4" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));run(()=>createAnnouncement(d),"Announcement published");e.currentTarget.reset();}}><input name="title" required placeholder="Title" className="border rounded-lg p-3"/><textarea name="content" required placeholder="Message" className="border rounded-lg p-3"/><div className="grid md:grid-cols-2 gap-3"><select name="audience" className="border rounded-lg p-3"><option value="all">Everyone</option><option value="members">Members</option><option value="registrants">Event registrants</option></select><select name="eventId" className="border rounded-lg p-3"><option value="">General announcement</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></div><button className="bg-primary text-white rounded-lg p-3">Publish</button></form></section>
    <section className="bg-white rounded-xl border p-6"><h2 className="font-bold text-xl">Send event reminder</h2><p className="text-sm text-gray-500 mt-1">Sends in-app and email reminders according to each member's notification preferences.</p><form className="grid gap-3 mt-4" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));run(()=>sendEventReminder(d.eventId,d.message),"Reminder queued for registrants");e.currentTarget.reset();}}><select name="eventId" required className="border rounded-lg p-3"><option value="">Choose event</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><textarea name="message" required placeholder="Reminder message" className="border rounded-lg p-3"/><button className="bg-primary text-white rounded-lg p-3">Send reminder</button></form></section>
    <section className="bg-white rounded-xl border p-6"><h2 className="font-bold text-xl">Ticket check-in</h2><p className="text-sm text-gray-500 mt-1">Paste the value from a scanned GGF ticket QR code.</p><form className="flex gap-3 mt-4" onSubmit={async e=>{e.preventDefault();const code=new FormData(e.currentTarget).get("code");const r=await checkInTicket(code);r.error?toast.error(r.error):(setCheckin(r),toast.success("Checked in"));}}><input name="code" required className="border rounded-lg p-3 flex-1" placeholder="GGF-TICKET:…"/><button className="bg-primary text-white px-5 rounded-lg">Check in</button></form>{checkin&&<p className="mt-3 bg-green-50 text-green-800 p-3 rounded-lg">{checkin.participant} checked in for {checkin.event}.</p>}</section>
    <section className="bg-white rounded-xl border p-6"><h2 className="font-bold text-xl">Create volunteer opportunity</h2><form className="grid md:grid-cols-2 gap-3 mt-4" onSubmit={e=>{e.preventDefault();run(()=>createVolunteerOpportunity(Object.fromEntries(new FormData(e.currentTarget))),"Volunteer opportunity created");e.currentTarget.reset();}}><input name="title" required placeholder="Title" className="border rounded-lg p-3"/><input name="location" placeholder="Location" className="border rounded-lg p-3"/><input name="eventDate" type="datetime-local" className="border rounded-lg p-3"/><input name="capacity" type="number" min="1" placeholder="Capacity" className="border rounded-lg p-3"/><textarea name="description" required placeholder="Description" className="border rounded-lg p-3 md:col-span-2"/><button className="bg-primary text-white rounded-lg p-3 md:col-span-2">Create</button></form></section>
    <section className="grid lg:grid-cols-2 gap-5"><div className="bg-white rounded-xl border p-6"><h2 className="font-bold text-xl">Opportunity review</h2>{opportunities.map(item=><div key={item.id} className="border-b py-3"><p className="font-semibold">{item.title}</p><p className="text-sm text-gray-500">{item.type} · {item.creator.firstName} {item.creator.surname}</p><div className="flex gap-3 mt-2"><button onClick={()=>run(()=>reviewOpportunity(item.id,true),"Approved")} className="text-green-700">Approve</button><button onClick={()=>run(()=>reviewOpportunity(item.id,false),"Rejected")} className="text-red-700">Reject</button></div></div>)}{!opportunities.length&&<p className="text-gray-500 mt-4">Nothing pending.</p>}</div><div className="bg-white rounded-xl border p-6"><h2 className="font-bold text-xl">Business review</h2>{businesses.map(item=><div key={item.id} className="border-b py-3"><p className="font-semibold">{item.name}</p><p className="text-sm text-gray-500">{item.category} · {item.user.firstName} {item.user.surname}</p><div className="flex gap-3 mt-2"><button onClick={()=>run(()=>reviewBusiness(item.id,true),"Approved")} className="text-green-700">Approve</button><button onClick={()=>run(()=>reviewBusiness(item.id,false),"Rejected")} className="text-red-700">Reject</button></div></div>)}{!businesses.length&&<p className="text-gray-500 mt-4">Nothing pending.</p>}</div></section>
    <section className="bg-white rounded-xl border p-6"><h2 className="font-bold text-xl">Volunteer applications</h2><div className="overflow-auto mt-4"><table className="w-full text-sm"><thead><tr className="text-left"><th className="p-2">Opportunity</th><th>Member</th><th>Status</th></tr></thead><tbody>{volunteers.map(item=><tr key={item.id} className="border-t"><td className="p-2">{item.opportunity.title}</td><td>{item.user.firstName} {item.user.surname}</td><td>{item.status}</td></tr>)}</tbody></table></div></section>
    <section className="bg-white rounded-xl border p-6"><h2 className="font-bold text-xl">Member safety reports</h2>{reports.map((report) => <div key={report.id} className="border-b py-3"><p className="font-semibold capitalize">{report.category}</p><p className="text-sm text-gray-600">{report.reporter.firstName} {report.reporter.surname} reported {report.subjectUser.firstName} {report.subjectUser.surname}</p>{report.details && <p className="text-sm mt-2">{report.details}</p>}<div className="flex gap-3 mt-2"><button onClick={() => run(() => reviewCommunityReport(report.id, "resolved"), "Report resolved")} className="text-green-700">Resolve</button><button onClick={() => run(() => reviewCommunityReport(report.id, "dismissed"), "Report dismissed")} className="text-gray-600">Dismiss</button></div></div>)}{!reports.length && <p className="text-gray-500 mt-4">No open reports.</p>}</section>
  </div>;
}
